name: "avt"
max_batch_size: 1
input {
  name: "input"
  data_type: TYPE_FP32
  dims: [ 1, 96, 96, 96 ]
}
output {
  name: "output"
  data_type: TYPE_FP32
  dims: [ 1, 96, 96, 96 ]
}

# GPU 실행을 위한 설정
instance_group {
  count: 1
  kind: KIND_GPU
  gpus: [ 0 ]
}
